/**
 * C4 — the name vocabulary, per docs/01-game-design.md §4.4: `[title] [given] [epithet]`.
 *
 * These are parts, not names. `tools/gen-names.ts` composes them offline into the
 * 200-name pools in `pools.gen.ts`; nothing at runtime touches this module except the
 * spec, which uses it to prove the generated pools were built from the right register.
 *
 * The registers are deliberately non-overlapping — warriors read as knightly, rangers
 * as woodland and watchful, rogues as scrappy and money-minded — because the pool a
 * name came from is the only thing telling the player what a hero is before it acts.
 *
 * An empty title means the name is given + epithet only ("Sylvaine Quickstep"). At most
 * one empty title per class, otherwise two different triples would compose to the same
 * string and the pool would lose a name to deduplication.
 */

export interface NameParts {
  readonly titles: readonly string[];
  readonly givens: readonly string[];
  readonly epithets: readonly string[];
}

const warrior: NameParts = {
  titles: [
    'Sir',
    'Dame',
    'Ser',
    'Lord',
    'Lady',
    'Warden',
    'Marshal',
    'Captain',
    'Bannerman',
    'Oathkeeper',
  ],
  givens: [
    'Caldwyn',
    'Hessa',
    'Aldric',
    'Berengar',
    'Rowan',
    'Godwin',
    'Maerid',
    'Tolvar',
    'Edrica',
    'Hallam',
    'Ivorn',
    'Brandt',
    'Selwyn',
    'Durran',
    'Wystan',
    'Aurelin',
    'Garrick',
    'Milbrand',
    'Odric',
    'Thessaly',
    'Ranulf',
    'Gwendra',
    'Harlan',
    'Bertrand',
    'Isolde',
    'Cadmar',
    'Elwyn',
    'Ferrold',
    'Marguerin',
    'Ostred',
    'Perrin',
    'Quintal',
    'Redmayne',
    'Sigurd',
    'Talwyn',
    'Ulric',
    'Vareth',
    'Wilhelmine',
    'Yorick',
    'Zephira',
  ],
  epithets: [
    'Broadedge',
    'Ironvow',
    'the Unyielding',
    'Shieldbearer',
    'the Stalwart',
    'Steelhand',
    'the Oathbound',
    'Grimward',
    'the Bulwark',
    'Hammerfall',
    'Truestrike',
    'the Undaunted',
    'Stonehelm',
    'the Bannerless',
    'Ironjaw',
    'the Resolute',
    'Wallbreaker',
    'the Dutiful',
    'Bloodwarden',
    'Keepfast',
    'the Sworn',
    'Longshield',
    'the Immovable',
    'Greycloak',
    'Vowkeeper',
  ],
};

const ranger: NameParts = {
  titles: ['', 'Scout', 'Pathfinder', 'Watcher', 'Tracker', 'Forester', 'Outrider', 'Keeper'],
  givens: [
    'Aelrindel',
    'Sylvaine',
    'Ilyra',
    'Faelan',
    'Norwenna',
    'Thalen',
    'Ceridwen',
    'Elowen',
    'Rhysand',
    'Maelis',
    'Vaeril',
    'Anwen',
    'Torren',
    'Lirien',
    'Bramwell',
    'Saoirse',
    'Eowain',
    'Nyrelle',
    'Cadfael',
    'Meriel',
    'Ashlen',
    'Fenwick',
    'Ysolde',
    'Corwin',
    'Thistra',
    'Emrys',
    'Lowena',
    'Aldren',
    'Sionna',
    'Veyla',
    'Hawthorn',
    'Rilka',
    'Ossian',
    'Brynn',
    'Talwen',
    'Kestrel',
    'Marren',
    'Ivywen',
    'Duskin',
    'Fernal',
  ],
  epithets: [
    'of the Long Watch',
    'Quickstep',
    'Greenhollow',
    'the Far-Seeing',
    'Thornwalker',
    'of the Silent Pines',
    'Nightleaf',
    'the Untraced',
    'Softtread',
    'of the North Ridge',
    'Windwhisper',
    'the Patient',
    'Elmshadow',
    'of the Grey Marches',
    'Swiftarrow',
    'the Wayfinding',
    'Mistrunner',
    'of the Hidden Vale',
    'Rootbound',
    'Farstride',
    'the Unseen',
    'Owlwatch',
    'of the Amber Wood',
    'Duskbow',
    'the Wandering',
  ],
};

const rogue: NameParts = {
  titles: ['', 'Little', 'Quick', 'Old', 'Lucky', 'Slippery', 'Handsome', 'Crooked'],
  givens: [
    'Skeev',
    'Marn',
    'Rikk',
    'Tobb',
    'Nessa',
    'Pell',
    'Gruv',
    'Wick',
    'Jessamy',
    'Corvo',
    'Bitters',
    'Nix',
    'Sallow',
    'Grib',
    'Teeva',
    'Rook',
    'Munn',
    'Prisk',
    'Dolla',
    'Vex',
    'Hobb',
    'Sparrow',
    'Crick',
    'Crank',
    'Mila',
    'Squill',
    'Tench',
    'Ambry',
    'Fisk',
    'Rowl',
    'Dunnock',
    'Kessa',
    'Pib',
    'Torvo',
    'Skellin',
    'Mott',
    'Wren',
    'Gilda',
    'Snick',
    'Halvo',
  ],
  epithets: [
    'Thinpurse',
    'the Unpaid',
    'Lightfingers',
    'the Debtless',
    'Coinbiter',
    'the Untaxed',
    'Quickpocket',
    'Pennyshort',
    'the Unhanged',
    'Cutpurse',
    'Halfshare',
    'the Overdue',
    'Ledgerless',
    'Backalley',
    'the Unaccounted',
    'Fivefinger',
    'Tallyburn',
    'the Never-Caught',
    'Coppercount',
    'Slipknot',
    'the Uninvited',
    'Dicefall',
    'Shortchange',
    'the Owed',
    'Emptyhand',
  ],
};

export const NAME_PARTS: Readonly<Record<'warrior' | 'ranger' | 'rogue', NameParts>> = {
  warrior,
  ranger,
  rogue,
};

/**
 * The six names printed in docs/01-game-design.md §4.4. They are seeded into the front
 * of each pool so the shipped content and the design document cannot drift apart.
 */
export const DOCUMENTED_NAMES: Readonly<
  Record<'warrior' | 'ranger' | 'rogue', readonly string[]>
> = {
  warrior: ['Sir Caldwyn Broadedge', 'Dame Hessa Ironvow'],
  ranger: ['Aelrindel of the Long Watch', 'Sylvaine Quickstep'],
  rogue: ['Skeev Thinpurse', 'Little Marn the Unpaid'],
};
