/**
 * The frozen contract. HUMAN-OWNED — see AGENTS.md §3.
 *
 * Agents propose changes here in their summary and stop; they do not edit this file.
 * If a task appears to need a change here, the contract is wrong and that is worth
 * saying out loud.
 *
 * Sources: docs/02-architecture.md §3, §9 · docs/04-ai-spec.md §2–§7
 */

import type { Rng } from './rng';

// ─────────────────────────────────────────────────────────────────────────────
// 1. Identity
// ─────────────────────────────────────────────────────────────────────────────

export type EntityId = number & { readonly __brand: 'EntityId' };

/**
 * Generational handle. Entities live in a recycled pool; a handle whose generation
 * no longer matches the slot is stale and detectable, rather than a dangling
 * reference or a leak.
 */
export interface Handle {
  readonly index: number;
  readonly generation: number;
}

export const NULL_HANDLE: Handle = { index: -1, generation: -1 };

export type FactionId = 'crown' | 'monsters' | 'neutral';

export type EntityKind =
  | 'hero'
  | 'monster'
  | 'henchman'
  | 'building'
  | 'lair'
  | 'flag'
  | 'prop';

export type ClassId = 'warrior' | 'ranger' | 'rogue';

export type HenchmanKind = 'peasant' | 'taxCollector' | 'guard';

export type MonsterKind = 'ratkin' | 'goblin' | 'goblinRaider';

/**
 * What an agent *is*, for goal weighting and action availability.
 *
 * Monsters run the same three-tier stack as heroes with different weights
 * (docs/04-ai-spec.md §9), which is a large architectural saving. That only works if
 * one type spans both, so goal multipliers and action class-gates key on this rather
 * than on ClassId.
 */
export type AgentKindId = ClassId | MonsterKind;

export type LairKind = 'ratkinWarren' | 'goblinCamp';

export type BuildingKind =
  | 'palace'
  | 'warriorsGuild'
  | 'roguesGuild'
  | 'rangersLodge'
  | 'marketplace'
  | 'blacksmith'
  | 'inn'
  | 'guardhouse';

// ─────────────────────────────────────────────────────────────────────────────
// 2. Space
// ─────────────────────────────────────────────────────────────────────────────

export interface TileCoord {
  readonly tx: number;
  readonly ty: number;
}

/** Continuous world position in tile units. `facing` indexes DIR8 (spatial/iso.ts). */
export interface Transform {
  x: number;
  y: number;
  facing: number;
}

export type Terrain = 'grass' | 'forest' | 'water' | 'rock' | 'road';

export type FogState = 0 | 1 | 2; // unseen · explored (stale) · visible

export const FOG_UNSEEN = 0 as const;
export const FOG_EXPLORED = 1 as const;
export const FOG_VISIBLE = 2 as const;

// ─────────────────────────────────────────────────────────────────────────────
// 3. Components
// ─────────────────────────────────────────────────────────────────────────────

export interface Health {
  hp: number;
  maxHp: number;
}

export interface Combat {
  damage: number;
  range: number;
  armour: number;
  /** Ticks between swings. 10 Hz sim: 1.2 s melee = 12, 1.6 s ranged = 16. */
  attackInterval: number;
  nextAttackTick: number;
  target: Handle;
  lastDamageFrom: Handle;
  lastDamageTick: number;
}

export interface Purse {
  gold: number;
}

export interface Movement {
  /** Tiles per second; the mover converts to per-tick internally. */
  speed: number;
  path: TileCoord[];
  pathIndex: number;
  /** Bumped by the grid on topology change; a stale path repaths lazily. */
  pathTopologyVersion: number;
  destination: TileCoord | null;
}

export type BuildingState = 'underConstruction' | 'complete' | 'damaged' | 'rubble';

export interface Building {
  kind: BuildingKind;
  state: BuildingState;
  /** 0..1 while underConstruction, 1 once complete. */
  progress: number;
  level: number;
  /** Gold banked here by heroes, drained by tax collectors. */
  vault: number;
  spawnCooldown: number;
  footprint: TileCoord[];
}

export interface Lair {
  kind: LairKind;
  wave: number;
  nextSpawnTick: number;
}

export type FlagKind = 'attack' | 'explore';

export interface Flag {
  kind: FlagKind;
  gold: number;
  target: Handle;
  tile: TileCoord;
  /** Claim cap is 3 — docs/01-game-design.md §8. */
  claimants: EntityId[];
  resolved: boolean;
}

export interface Equipment {
  weaponTier: 0 | 1 | 2;
  armourTier: 0 | 1 | 2;
  potions: number;
}

export interface Progression {
  level: number;
  xp: number;
}

export interface Renderable {
  /** Index into the generated atlas frame constants. */
  frame: number;
  tint: number;
  /** Previous transform, for tick-alpha interpolation in render/. */
  prevX: number;
  prevY: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. AI — tier 1 traits and goals
// ─────────────────────────────────────────────────────────────────────────────

export type TraitId = 'greed' | 'courage' | 'curiosity' | 'loyalty';

export type Traits = Record<TraitId, number>;

export type GoalId =
  | 'Survive'
  | 'Heal'
  | 'ClaimBounty'
  | 'HuntMonster'
  | 'DefendHome'
  | 'Upgrade'
  | 'Explore'
  | 'Idle'
  | 'AttackStructure'
  | 'AttackHenchman';

/** A 256-entry LUT family with three trait variants — docs/03-determinism.md §4.1. */
export interface CurveFamily {
  readonly TIMID: Uint16Array;
  readonly NEUTRAL: Uint16Array;
  readonly BOLD: Uint16Array;
}

export interface Consideration {
  readonly id: string;
  /** Must return an already-normalised 0..1 value. */
  input(a: Agent, w: WorldView): number;
  readonly family: CurveFamily;
  /** When set, selects and blends curve variants by the agent's trait value. */
  readonly trait?: TraitId;
  /**
   * Flips the trait axis for this consideration: a *higher* trait produces a
   * *weaker* response.
   *
   * Needed exactly once, and the exception is instructive. Everywhere else a high
   * trait means "react more" — a greedy hero values the same bounty more, a curious
   * one is less put off by distance. But Survive is the goal of *not* fighting, and
   * courage must lower it, not raise it. Rather than invert the curve family and
   * break the one-direction convention everywhere else, the trait axis flips here.
   */
  readonly traitInverted?: boolean;
}

export interface GoalDef {
  readonly id: GoalId;
  /** At most 5 — docs/04-ai-spec.md §5. */
  readonly considerations: readonly Consideration[];
  /** Absent means the goal is unavailable to that kind; 1.0 is the neutral weight. */
  readonly classMultiplier: Readonly<Partial<Record<AgentKindId, number>>>;
  /** The planner's target state for this goal. */
  readonly target: State;
  /** Survive and DefendHome re-score outside the stagger schedule. */
  readonly interruptible: boolean;
}

export interface ScoreBreakdown {
  goalId: GoalId;
  score: number;
  /** Per-consideration curve outputs, retained for the Hero Inspector. */
  parts: number[];
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. AI — tier 2 planning state
// ─────────────────────────────────────────────────────────────────────────────

/** Symbolic planning vocabulary — docs/04-ai-spec.md §2. */
export const enum S {
  HAS_GOLD = 1 << 0,
  AT_TARGET = 1 << 1,
  TARGET_DEAD = 1 << 2,
  TARGET_KNOWN = 1 << 3,
  IS_INJURED = 1 << 4,
  IS_CRITICAL = 1 << 5,
  HAS_POTION = 1 << 6,
  AT_MARKET = 1 << 7,
  AT_SMITH = 1 << 8,
  AT_INN = 1 << 9,
  AT_HOME_GUILD = 1 << 10,
  THREAT_NEARBY = 1 << 11,
  BOUNTY_KNOWN = 1 << 12,
  LAIR_KNOWN = 1 << 13,
  UPGRADE_AVAILABLE = 1 << 14,
  IS_RESTED = 1 << 15,
  SAFE = 1 << 16,
}

/** `mask` marks which symbols are constrained; `values` holds their truth. */
export interface State {
  values: number;
  mask: number;
}

export type ActionId =
  | 'MoveToTarget'
  | 'MoveToMarket'
  | 'MoveToSmith'
  | 'MoveToInn'
  | 'MoveToGuild'
  | 'Attack'
  | 'ClaimBounty'
  | 'LootCorpse'
  | 'BuyPotion'
  | 'DrinkPotion'
  | 'BuyUpgrade'
  | 'RestAtInn'
  | 'HealAtGuild'
  | 'Flee'
  | 'ExploreTile'
  | 'Idle';

export type StepResult = 'running' | 'success' | 'failure';

export interface ActionRuntime {
  start(a: Agent, w: WorldView): void;
  tick(a: Agent, w: WorldView): StepResult;
  stillValid(a: Agent, w: WorldView): boolean;
  abort(a: Agent, w: WorldView): void;
}

export interface ActionDef {
  readonly id: ActionId;
  readonly pre: State;
  readonly eff: State;
  readonly classes: readonly AgentKindId[] | 'all';
  cost(a: Agent, w: WorldView): number;
  /** Contextual gate checked during search — cheap, no world mutation. */
  isValid(a: Agent, w: WorldView): boolean;
  /** Resolves the concrete target onto the blackboard. */
  bind(a: Agent, w: WorldView): boolean;
  readonly runtime: ActionRuntime;
}

export interface PlanStep {
  action: ActionId;
  cost: number;
}

export interface Plan {
  goalId: GoalId;
  steps: PlanStep[];
  index: number;
  /** Union of every step's precondition mask; a flip here invalidates the plan. */
  accumulatedMask: number;
  totalCost: number;
  createdTick: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. AI — sensing
// ─────────────────────────────────────────────────────────────────────────────

export interface FlagKnowledge {
  id: EntityId;
  gold: number;
  tile: TileCoord;
}

export interface Blackboard {
  visibleEnemies: Handle[];
  nearestThreat: Handle;
  nearestShop: { market: Handle; smith: Handle; inn: Handle };
  homeGuild: Handle;
  knownLairs: Set<EntityId>;
  knownFlags: FlagKnowledge[];
  currentTarget: Handle;
  lastDamageFrom: Handle;
  /** Nearest friendly building currently taking damage — DefendHome scores on it. */
  damagedBuilding: Handle;
  frontierTile: TileCoord | null;
  /** Tick each sensor last ran, indexed by sensor id. */
  sensorDue: Record<string, number>;
}

export interface GoalSwitch {
  tick: number;
  from: GoalId | null;
  to: GoalId;
  trigger: 'stagger' | 'interrupt' | 'planFailure' | 'actionFailure';
}

export interface Agent {
  entity: Handle;
  classId: AgentKindId;
  name: string;
  traits: Traits;

  currentGoal: GoalId | null;
  goalScores: ScoreBreakdown[];
  plan: Plan | null;
  currentState: State;

  blackboard: Blackboard;

  nextGoalTick: number;
  nextPlanTick: number;

  /** Ring buffer of the last 10 switches — the Hero Inspector reads this. */
  history: GoalSwitch[];
  idleSinceTick: number;
}

export interface FsmState {
  kind: HenchmanKind;
  state: string;
  timer: number;
  post: TileCoord | null;
  carrying: number;
  targetSite: Handle;
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. The entity
// ─────────────────────────────────────────────────────────────────────────────

export interface Entity {
  id: EntityId;
  handle: Handle;
  kind: EntityKind;
  faction: FactionId;
  transform: Transform;
  alive: boolean;

  health?: Health;
  combat?: Combat;
  movement?: Movement;
  purse?: Purse;
  equipment?: Equipment;
  progression?: Progression;

  agent?: Agent;
  fsm?: FsmState;

  building?: Building;
  lair?: Lair;
  flag?: Flag;
  renderable?: Renderable;
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. Commands — docs/02-architecture.md §9
// ─────────────────────────────────────────────────────────────────────────────

export type Command =
  | { t: 'PLACE_BUILDING'; kind: BuildingKind; tile: TileCoord }
  | { t: 'PLACE_FLAG'; kind: FlagKind; target: Handle | TileCoord; gold: number }
  | { t: 'CANCEL_FLAG'; id: EntityId }
  | { t: 'SET_TAX_RATE'; rate: number }
  | { t: 'DEMOLISH'; id: EntityId };

/** `(seed, commandLog)` is the complete save file. */
export interface CommandLogEntry {
  tick: number;
  command: Command;
}

// ─────────────────────────────────────────────────────────────────────────────
// 9. Events — render and UI read these; core never reads back
// ─────────────────────────────────────────────────────────────────────────────

export type WorldEvent =
  | { t: 'DAMAGE'; target: EntityId; amount: number; from: EntityId }
  | { t: 'DEATH'; entity: EntityId; killer: EntityId | null }
  | { t: 'SPAWN'; entity: EntityId; kind: EntityKind }
  | { t: 'GOLD'; entity: EntityId; delta: number; reason: string }
  | { t: 'BUILD_COMPLETE'; entity: EntityId }
  | { t: 'FLAG_CLAIMED'; flag: EntityId; by: EntityId; gold: number }
  | { t: 'LEVEL_UP'; entity: EntityId; level: number };

// ─────────────────────────────────────────────────────────────────────────────
// 10. Snapshot — the read-only surface render/ and ui/ are allowed to touch
// ─────────────────────────────────────────────────────────────────────────────

export interface Snapshot {
  tick: number;
  treasury: number;
  escrow: number;
  taxRate: number;
  palaceLevel: number;
  population: { heroes: number; henchmen: number; monsters: number };
  wave: number;
  entities: readonly Entity[];
  events: readonly WorldEvent[];
  outcome: 'playing' | 'won' | 'lost';
}

/**
 * What systems and AI are handed. Deliberately narrower than the concrete World so a
 * consideration cannot mutate the simulation while scoring.
 */
export interface WorldView {
  readonly tick: number;
  readonly treasury: number;
  readonly taxRate: number;
  readonly rng: Rng;
  get(h: Handle): Entity | null;
  byId(id: EntityId): Entity | null;
  isAlive(h: Handle): boolean;
  entitiesInIdOrder(): Iterable<Entity>;
}

export interface PlannerStats {
  hits: number;
  misses: number;
  nullPlans: number;
  attempts: number;
  expansions: number;
}
