import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { decodePng, encodePng } from './png';

const SOURCE = 'public/atlas/src'; const OUT = 'public/atlas'; const SIZE = 1024; const BORDER = 2;
interface Frame { frame: { x: number; y: number; w: number; h: number }; rotated: false; trimmed: false; spriteSourceSize: { x: 0; y: 0; w: number; h: number }; sourceSize: { w: number; h: number }; }
async function main(): Promise<void> {
  const files = (await readdir(SOURCE)).filter((name) => name.endsWith('.png')).sort(); if (files.length === 0) throw new Error('No source sprites. Run make-placeholders first.');
  const atlas = new Uint8Array(SIZE * SIZE * 4); const frames: Record<string, Frame> = {}; let x = BORDER, y = BORDER, row = 0;
  for (const file of files) { const png = decodePng(await readFile(join(SOURCE, file))); if (x + png.width + BORDER > SIZE) { x = BORDER; y += row + BORDER; row = 0; } if (y + png.height + BORDER > SIZE) throw new Error('Stage A atlas exceeds 1024px.'); const name = file.slice(0, -4); frames[name] = { frame: { x, y, w: png.width, h: png.height }, rotated: false, trimmed: false, spriteSourceSize: { x: 0, y: 0, w: png.width, h: png.height }, sourceSize: { w: png.width, h: png.height } }; for (let yy = 0; yy < png.height; yy++) atlas.set(png.pixels.subarray(yy * png.width * 4, (yy + 1) * png.width * 4), ((y + yy) * SIZE + x) * 4); x += png.width + BORDER; row = Math.max(row, png.height); }
  const image = encodePng({ width: SIZE, height: SIZE, pixels: atlas }); await writeFile(join(OUT, 'game.png'), image); await writeFile(join(OUT, 'game.json'), `${JSON.stringify({ frames, meta: { image: 'game.png', format: 'RGBA8888', size: { w: SIZE, h: SIZE }, scale: '1' } }, null, 2)}\n`);
  const names = Object.keys(frames); const lines = ['/** Generated by tools/build-atlas.ts. Do not edit. */', `export const FRAME_NAMES = ${JSON.stringify(names, null, 2)} as const;`, 'export type FrameName = (typeof FRAME_NAMES)[number];', 'export const FRAMES = Object.fromEntries(FRAME_NAMES.map((name, index) => [name, index])) as Readonly<Record<FrameName, number>>;']; await writeFile('src/render/frames.gen.ts', `${lines.join('\n')}\n`);
  const hash = createHash('sha256').update(image).digest('hex'); await writeFile('public/assets.manifest.json', `${JSON.stringify([{ name: 'stage-a-procedural-atlas', url: 'self-made', license: 'self-made', author: 'Rival Sovereigns contributors', sourcePage: 'tools/make-placeholders.ts', sha256: hash }], null, 2)}\n`);
  console.log(`build-atlas: packed ${names.length} frames into ${OUT}/game.png`);
}
void main();
