/**
 * C1 — generates src/core/ai/curves.gen.ts.
 *
 * Runs in Node at build time, so Math.pow is legal HERE and nowhere downstream.
 * That is the entire point: the exponent is evaluated once, offline, and the
 * simulation only ever reads integers out of a table. See docs/03-determinism.md §4.1.
 *
 *   pnpm pregen
 *
 * The output is checked in. Regenerating must be idempotent — if this file produces a
 * diff without an intentional change to the curve definitions, that is a bug.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ENTRIES = 256;
const MAX = 65535;

/** Trait variants. A trait value selects two of these and lerps — never an exponent. */
const VARIANTS = { TIMID: 0.5, NEUTRAL: 1.0, BOLD: 1.8 } as const;

/**
 * Six families. `shape` receives x in 0..1 and the variant exponent k, and returns
 * 0..1.
 *
 * Two invariants hold across every family, and tuning depends on both:
 *
 *   1. Monotonic in x, so a score is always explainable as "more of this input
 *      pushed the number this way".
 *   2. **A higher trait always means a stronger response to the same input.** The
 *      variant exponents are fixed by docs/03-determinism.md §4.1 (TIMID 0.5,
 *      NEUTRAL 1.0, BOLD 1.8), so each family divides by k rather than raising to
 *      it — otherwise BOLD would make a hero *more* danger-averse, which is
 *      backwards for every consideration that uses courage.
 *
 * NEUTRAL (k = 1) is the plain shape in every case.
 */
const FAMILIES: Record<string, (x: number, k: number) => number> = {
  // Rises steadily. "More is better."
  LINEAR: (x, k) => Math.pow(x, 1 / k),

  // Falls as x rises. The workhorse: distance, danger, threat ratio.
  INVERSE: (x, k) => Math.pow(1 - x, 1 / k),

  // LINEAR with a cliff, for thresholds that should feel abrupt.
  STEEP: (x, k) => Math.pow(x, 2.5 / k),

  // Sharper INVERSE — Survive uses it on hp ratio, where 25% must feel very
  // different from 50%.
  INVERSE_STEEP: (x, k) => Math.pow(1 - x, 2.5 / k),

  // Rises fast then flattens. "Enough is enough" — gold on hand, bounty size.
  SATURATING: (x, k) => Math.pow(x, 0.45 / k),

  // Holds near 1, then falls away. Diminishing aversion.
  INVERSE_SATURATING: (x, k) => Math.pow(1 - x, 0.45 / k),
};

function table(shape: (x: number, k: number) => number, k: number): number[] {
  const out: number[] = [];
  for (let i = 0; i < ENTRIES; i++) {
    const x = i / (ENTRIES - 1);
    const y = shape(x, k);
    const clamped = y < 0 ? 0 : y > 1 ? 1 : y;
    out.push(Math.round(clamped * MAX));
  }
  return out;
}

function formatTable(values: number[]): string {
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += 16) {
    lines.push('  ' + values.slice(i, i + 16).join(', ') + ',');
  }
  return lines.join('\n');
}

const parts: string[] = [
  '/**',
  ' * GENERATED by tools/gen-curves.ts — do not edit. Run `pnpm pregen`.',
  ' *',
  ' * 256-entry integer response curves. The exponents that shaped these were evaluated',
  ' * once, in Node, at build time. Nothing downstream may reintroduce one — see',
  ' * docs/03-determinism.md §4.1 and AGENTS.md §6.',
  ' */',
  '',
  "import type { CurveFamily } from '../types';",
  '',
];

for (const [family, shape] of Object.entries(FAMILIES)) {
  for (const [variant, k] of Object.entries(VARIANTS)) {
    parts.push(`const ${family}_${variant} = new Uint16Array([`);
    parts.push(formatTable(table(shape, k)));
    parts.push(']);', '');
  }
}

for (const family of Object.keys(FAMILIES)) {
  parts.push(
    `export const ${family}: CurveFamily = {`,
    `  TIMID: ${family}_TIMID,`,
    `  NEUTRAL: ${family}_NEUTRAL,`,
    `  BOLD: ${family}_BOLD,`,
    '};',
    '',
  );
}

parts.push(
  'export const CURVE_FAMILIES = {',
  ...Object.keys(FAMILIES).map((f) => `  ${f},`),
  '} as const;',
  '',
  'export type CurveFamilyName = keyof typeof CURVE_FAMILIES;',
  '',
);

const target = resolve(import.meta.dirname, '../src/core/ai/curves.gen.ts');
writeFileSync(target, parts.join('\n'), 'utf8');
console.log(
  `gen-curves: ${Object.keys(FAMILIES).length} families x ${Object.keys(VARIANTS).length} variants x ${ENTRIES} entries -> ${target}`,
);
