/**
 * C4 — generates src/content/names/pools.gen.ts.
 *
 * Runs in Node at build time. The 200 names per class are composed here, once, and
 * checked in; at runtime `pickName` only ever indexes the resulting array with one draw
 * from the world RNG. docs/07-backlog.md C4: "generated offline, deterministic index at
 * runtime".
 *
 *   pnpm pregen
 *
 * The output is checked in and regenerating must be idempotent. There is no randomness
 * in here at all — not even a seeded generator — because the walk below is what picks
 * the combinations, and it is pure arithmetic on the part lists.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { NAME_PARTS, DOCUMENTED_NAMES, type NameParts } from '../src/content/names/parts';

const POOL_SIZE = 200;

/**
 * One stride per class, walked modulo the full combination count.
 *
 * Taking every Kth combination of a mixed-radix (title, given, epithet) index is a full
 * cycle whenever K is coprime with the combination count, so the first 200 steps are
 * guaranteed distinct triples — uniqueness by construction rather than by hoping 200
 * random draws miss each other. A large stride also means consecutive names differ in
 * all three parts, which matters because the pool is read in order by anyone eyeballing
 * the generated file.
 */
const STRIDES: Record<string, number> = {
  warrior: 3571,
  ranger: 2137,
  rogue: 4409,
};

function gcd(a: number, b: number): number {
  let x = a;
  let y = b;
  while (y !== 0) {
    const t = x % y;
    x = y;
    y = t;
  }
  return x;
}

function compose(parts: NameParts, index: number): string {
  const { titles, givens, epithets } = parts;
  const epithet = epithets[index % epithets.length];
  const given = givens[Math.floor(index / epithets.length) % givens.length];
  const title = titles[Math.floor(index / (epithets.length * givens.length)) % titles.length];
  if (epithet === undefined || given === undefined || title === undefined) {
    throw new Error(`gen-names: index ${index} fell outside the part lists`);
  }
  return title === '' ? `${given} ${epithet}` : `${title} ${given} ${epithet}`;
}

function buildPool(classId: string, parts: NameParts, seeds: readonly string[]): string[] {
  const combinations = parts.titles.length * parts.givens.length * parts.epithets.length;
  const stride = STRIDES[classId];
  if (stride === undefined) throw new Error(`gen-names: no stride for class "${classId}"`);
  if (gcd(stride, combinations) !== 1) {
    throw new Error(
      `gen-names: stride ${stride} is not coprime with ${combinations} combinations for ` +
        `"${classId}" — the walk would repeat before ${POOL_SIZE} names`,
    );
  }
  if (combinations < POOL_SIZE) {
    throw new Error(`gen-names: "${classId}" has only ${combinations} combinations`);
  }
  if (parts.titles.filter((t) => t === '').length > 1) {
    throw new Error(`gen-names: "${classId}" has more than one empty title`);
  }

  const seen = new Set<string>(seeds);
  const pool = [...seeds];
  for (let step = 0; pool.length < POOL_SIZE; step++) {
    if (step >= combinations) {
      throw new Error(`gen-names: exhausted "${classId}" before reaching ${POOL_SIZE} names`);
    }
    const name = compose(parts, (step * stride) % combinations);
    if (seen.has(name)) continue;
    seen.add(name);
    pool.push(name);
  }
  return pool;
}

const pools: Record<string, string[]> = {};
for (const classId of Object.keys(NAME_PARTS).sort()) {
  const parts = NAME_PARTS[classId as keyof typeof NAME_PARTS];
  const seeds = DOCUMENTED_NAMES[classId as keyof typeof DOCUMENTED_NAMES];
  pools[classId] = buildPool(classId, parts, seeds);
}

// A name shared between two pools would make the class unreadable from the name alone,
// which is the whole reason the pools are separate. Catch it here rather than in review.
const owner = new Map<string, string>();
for (const [classId, pool] of Object.entries(pools)) {
  for (const name of pool) {
    const previous = owner.get(name);
    if (previous !== undefined) {
      throw new Error(`gen-names: "${name}" appears in both "${previous}" and "${classId}"`);
    }
    owner.set(name, classId);
    if (name.includes("'") || name.includes('\\')) {
      throw new Error(`gen-names: "${name}" cannot be emitted as a single-quoted literal`);
    }
  }
}

const CONST_NAMES: Record<string, string> = {
  warrior: 'WARRIOR_NAMES',
  ranger: 'RANGER_NAMES',
  rogue: 'ROGUE_NAMES',
};

const lines: string[] = [
  '/**',
  ' * GENERATED by tools/gen-names.ts — do not edit. Run `pnpm pregen`.',
  ' *',
  ` * ${POOL_SIZE} names per class in the \`[title] [given] [epithet]\` form of`,
  ' * docs/01-game-design.md §4.4, composed offline from src/content/names/parts.ts.',
  ' * Runtime selection is a single indexed read — see ./index.ts.',
  ' */',
  '',
];

for (const classId of ['warrior', 'ranger', 'rogue']) {
  const pool = pools[classId];
  const constName = CONST_NAMES[classId];
  if (pool === undefined || constName === undefined) {
    throw new Error(`gen-names: missing output for "${classId}"`);
  }
  lines.push(`export const ${constName}: readonly string[] = [`);
  for (const name of pool) lines.push(`  '${name}',`);
  lines.push('];', '');
}

const target = resolve(import.meta.dirname, '../src/content/names/pools.gen.ts');
writeFileSync(target, lines.join('\n'), 'utf8');
console.log(`gen-names: 3 classes x ${POOL_SIZE} names -> ${target}`);
