/**
 * C10 — builds CREDITS.md from assets.manifest.json.
 *
 *   pnpm credits          rewrite CREDITS.md
 *   pnpm credits:check    fail if CREDITS.md is missing or stale (runs in `prebuild`)
 *
 * docs/AGENTS.md §5: "Licensing is a hard gate." This file is where that gate has
 * teeth. It refuses to emit credits for any asset lacking a confirmed licence, a
 * named author, or a citable source, and it exits non-zero when it refuses — so a
 * build that would ship an unattributed asset does not produce a build at all.
 *
 * The output is deterministic: entries are sorted by id and nothing is stamped with a
 * date or a version. Regenerating without a manifest change must produce no diff.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  type AssetEntry,
  type AssetManifest,
  REPO_ROOT,
  assertLicensed,
  loadManifest,
  parseManifest,
} from './fetch-assets';

export const CREDITS_PATH = resolve(REPO_ROOT, 'CREDITS.md');

const HEADER = [
  '# Credits',
  '',
  '<!-- Generated by `pnpm credits` from assets.manifest.json. Do not edit by hand. -->',
  '',
  'Every third-party asset in this project is CC0, CC-BY, or self-made, and every one of',
  'them is declared in `assets.manifest.json` with the page its licence was read from and',
  'the SHA-256 of the exact bytes that licence was confirmed against. Adding an asset any',
  'other way fails the build — see `docs/AGENTS.md` §5.',
  '',
];

const EMPTY_BODY = [
  '## Third-party assets',
  '',
  '_None. Every asset currently in the project is generated by `tools/make-placeholders.ts`._',
  '',
];

/**
 * Rendered as a bullet list rather than a markdown table on purpose: Prettier pads
 * table columns to their widest cell, so a table would be reformatted the first time
 * anyone ran `pnpm format` and `credits:check` would then fail on a file nobody
 * edited. A bullet list is a fixed point of the formatter.
 */
function renderEntry(asset: AssetEntry): string[] {
  const lines = [`### ${asset.title}`, ''];

  lines.push(`- **Author** — ${asset.author}`);
  lines.push(
    `- **Licence** — ${asset.licenceUrl ? `[${asset.licence}](${asset.licenceUrl})` : asset.licence}`,
  );
  if (asset.sourcePage) lines.push(`- **Source** — <${asset.sourcePage}>`);
  if (asset.downloadUrl) lines.push(`- **Download** — <${asset.downloadUrl}>`);
  if (asset.sha256) lines.push(`- **SHA-256** — \`${asset.sha256}\``);
  lines.push(`- **Path** — \`${asset.path}\``);
  lines.push('');

  if (asset.note) lines.push(asset.note, '');

  return lines;
}

/**
 * Renders CREDITS.md. Throws `LicenceGateError` — via `assertLicensed` — before
 * producing a single byte if any entry is not fully licensed and attributable.
 */
export function renderCredits(manifest: AssetManifest): string {
  assertLicensed(manifest.assets);

  // Sort by id, not by array order: the file is a diff surface, and the manifest's
  // order is an authoring convenience nobody should have to keep stable by hand.
  const sorted = [...manifest.assets].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  const body =
    sorted.length === 0
      ? EMPTY_BODY
      : ['## Third-party assets', '', ...sorted.flatMap((asset) => renderEntry(asset))];

  return [...HEADER, ...body].join('\n');
}

/**
 * The full pipeline from raw JSON, which is what the acceptance test drives: a bad
 * entry must fail somewhere in here, not merely fail to be pretty-printed.
 */
export function creditsFromRaw(raw: unknown): string {
  return renderCredits(parseManifest(raw));
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

async function main(argv: readonly string[]): Promise<void> {
  const check = argv.includes('--check');
  const manifest = await loadManifest();
  const rendered = renderCredits(manifest);

  if (check) {
    let current: string | null = null;
    try {
      current = await readFile(CREDITS_PATH, 'utf8');
    } catch {
      current = null;
    }
    if (current !== rendered) {
      throw new Error(
        `CREDITS.md is ${current === null ? 'missing' : 'out of date'}. Run \`pnpm credits\` and commit the result.`,
      );
    }
    console.log(`gen-credits: CREDITS.md is up to date (${manifest.assets.length} asset(s))`);
    return;
  }

  await writeFile(CREDITS_PATH, rendered, 'utf8');
  console.log(`gen-credits: ${manifest.assets.length} asset(s) -> ${CREDITS_PATH}`);
}

const invokedPath = process.argv[1];
if (invokedPath !== undefined && resolve(invokedPath) === fileURLToPath(import.meta.url)) {
  try {
    await main(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
